### ISSUE TITLE
Strobing buttons and numbers in filter

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/clean-and-green-philly#601]
In the filter when you click on one of the button badges the background flashed or strobes light, dark, light, dark, light, dark. For most people this just feels janky. For people with epilepsy strobing effects can induce seizures, so I would assume in this small amount it would likely be at least unsettling for them. 

Also as you filter the number of properity jumps to one number and switches to another. 

These two issues might be related or might not be. 

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/ea22ea01-543c-490f-a7da-efc7929f248d

**Comment by jgrimes86** [comment]
@thansidwell the strobing button color has been on my mind, so I've been looking into a fix.  I think I've resolved that issue.  I don't know if this also affects the numbers issue, because I didn't see that on my local version of the app.

Can I make a pull request so you can see how it works on your end?

https://github.com/CodeForPhilly/clean-and-green-philly/assets/140654473/59e1062d-e0f5-4d50-aab7-a8ef022f9305
