### ISSUE TITLE
Task: Audit performance of About page

### ISSUE THREAD

**Issue by CodeWritingCow** [CodeForPhilly/clean-and-green-philly#737]
## Describe the task

Audit performance of Clean and Green Philly's [About This Project](https://www.cleanandgreenphilly.org/about) page using Google Lighthouse. Document audit results, including areas of improvement.

## Acceptance Criteria

- [ ] Generate Lighthouse report for mobile devices
- [ ] Generate Lighthouse report for desktop devices
- [ ] Post screenshots of results in this issue's comments section
- [ ] Write brief summary of audit highlights, including Lighthouse's recommendations for improvement

## Additional context

* For instructions on using Lighthouse, see https://developer.chrome.com/docs/lighthouse/overview

**Comment by zheyichn** [comment]
Hi, can I be assigned this issue pls?

**Comment by CodeWritingCow** [comment]
@zheyichn it's yours!

**Comment by zheyichn** [comment]
## Lighthouse report on mobile devices

- Performance score was 70/100. Score took a bit hit because the loading of the map image took 7.1 seconds.
- Accessibility score was 95/100 due to `<nav>` element shoudn't have `aria-passed` attribute as mentioned in #727.
- SEO score was 82/100. Penalty comes from links do not have descriptive text & links not crawlable.

### Screenshoots
<img width="776" alt="about-mobile-1" src="https://github.com/user-attachments/assets/114a18f0-a37d-432a-a168-1b08da1ae629">

<img width="776" alt="about-mobile-2" src="https://github.com/user-attachments/assets/c5d72bdc-467d-4530-b6e2-c5951010456f">

<img width="776" alt="about-mobile-3" src="https://github.com/user-attachments/assets/8ea1a97e-ad49-464f-a583-bfa5a0b450a5">

<img width="776" alt="about-mobile-3 1" src="https://github.com/user-attachments/assets/8ad37b65-cf39-4e0f-8287-4204a284a867">

<img width="776" alt="about-mobile-4" src="https://github.com/user-attachments/assets/49a3c9a2-be4c-4c86-b6de-55f102733f61">

<img width="776" alt="about-mobile-5" src="https://github.com/user-attachments/assets/6727fe66-a005-4663-9a31-159bb06aaeb0">

**Comment by zheyichn** [comment]
## Lighthouse report for desktop devices

- Performance score was 97/100. Large Contentful Paint took 1.3 seconds.
- Accessibility score was 95/100 because of having `aria-pressed` attribute on `<nav>` elements.
- SEO score was 82/100, since links do not have descriptive text & links being not crawlable.

### Screenshoots
<img width="737" alt="about-desk-1" src="https://github.com/user-attachments/assets/4ba5888d-a3ec-4f47-85cf-ac7a00f90869">

<img width="708" alt="about-desk-2" src="https://github.com/user-attachments/assets/66f24b5f-d6f3-4292-8944-98b313245a1f">

<img width="708" alt="about-desk-3" src="https://github.com/user-attachments/assets/d8340027-03bc-4037-b8a8-4c044d8da951">

<img width="708" alt="about-desk-4" src="https://github.com/user-attachments/assets/1184d709-252b-446f-9bf3-224f7aed2888">

<img width="729" alt="about-desk-5" src="https://github.com/user-attachments/assets/29025749-a1a3-4985-bbc0-5a9759128942">

<img width="729" alt="about-desk-6" src="https://github.com/user-attachments/assets/bfc89d46-276f-43fe-808c-74349c34f9bd">

**Comment by zheyichn** [comment]
## Summary
- Performance got penalty from long image loading time, mianly for mobile devices.
- Accessibility was good on both devices. #727 provided context for why this page did not get full score.
- SEO suggests links to be crawlable and have descriptive text.
## Improvement recommendations

### For mobile devices
1. Explore ways to reduce the map image loading time. (Performance) 
2. Make links crawlable to search engine and add descriptive text. (SEO)
### For desktop devices
1. Make links crawlable to search engine and add descriptive text. (SEO)

**Comment by nlebovits** [comment]
@CodeWritingCow please add to your list to review
