### ISSUE TITLE
Task: Audit performance of Accessibility Conformance Report (VPAT) page

### ISSUE THREAD

**Issue by CodeWritingCow** [CodeForPhilly/clean-and-green-philly#741]
## Describe the task

Audit performance of Clean and Green Philly's [Accessibility Conformance Report (VPAT)](https://www.cleanandgreenphilly.org/vpat) page using Google Lighthouse. Document audit results, including areas of improvement.

## Acceptance Criteria

- [ ] Generate Lighthouse report for mobile devices
- [ ] Generate Lighthouse report for desktop devices
- [ ] Post screenshots of results in this issue's comments section
- [ ] Write brief summary of audit highlights, including Lighthouse's recommendations for improvement

## Additional context

* For instructions on using Lighthouse, see https://developer.chrome.com/docs/lighthouse/overview

**Comment by zheyichn** [comment]
Hi, can I be assigned this ticket pls?

**Comment by CodeWritingCow** [comment]
@zheyichn assigned!

**Comment by zheyichn** [comment]
## Lighthouse report for mobile devices
- Performance score was 69/100. It took a big hit due to `largest contentful paint` time of 7.1 seconds, and a `total blocking time` of 340ms.
### Screenshots
<img width="754" alt="vapt-mobile-1" src="https://github.com/user-attachments/assets/62992dc5-b6a1-40c8-a7ca-9aebbd49daf7">
<img width="754" alt="vpat-mobile-2" src="https://github.com/user-attachments/assets/5ecd1906-d713-4f88-9afd-e33ae075c2d2">
<img width="613" alt="vpat-mobile-3" src="https://github.com/user-attachments/assets/13680cb5-621d-40b3-af52-96827f68ffe2">
<img width="613" alt="vpat-mobile-4" src="https://github.com/user-attachments/assets/e193b035-6563-48ad-b747-6d2bfc4b68d5">
<img width="613" alt="vpat-mobile-5" src="https://github.com/user-attachments/assets/fd6ff2a6-bff9-4a52-aeeb-d1f8104dd9a1">
<img width="613" alt="vpat-mobile-6" src="https://github.com/user-attachments/assets/9aba7e80-3da6-452e-872d-6500f90da4a8">
<img width="613" alt="vpat-mobile-7" src="https://github.com/user-attachments/assets/79d7830b-bb01-40f3-9788-ae56bdd4db8f">

**Comment by zheyichn** [comment]
## Lighthouse report for desktop devices
- All four scores were above 90/100. 
- Accessibility can be further improved by increasing contrast ratio for some table titles.
### Screenshots
<img width="613" alt="vpat-desktop-8" src="https://github.com/user-attachments/assets/b0c015bc-72d2-48c8-875b-3bed505adce3">
<img width="613" alt="vpat-desktop-9" src="https://github.com/user-attachments/assets/5b1c7ae8-be34-439c-8b1d-21cc5e181c2d">
<img width="613" alt="vpat-desktop-10" src="https://github.com/user-attachments/assets/99c4663a-f3e0-4e00-bb49-7d77a791679c">
<img width="613" alt="vpat-desktop-11" src="https://github.com/user-attachments/assets/51f2c683-e576-4a0c-8877-1a4b3bd7d304">
<img width="613" alt="vpat-desktop-12" src="https://github.com/user-attachments/assets/2aff528d-057c-4d82-956a-b804f4ba4d3a">
<img width="613" alt="vpat-desktop-13" src="https://github.com/user-attachments/assets/2e5ddb05-3e34-4c50-a69f-4d7da4784de1">
<img width="613" alt="vpat-desktop-14" src="https://github.com/user-attachments/assets/c8d311da-e3b3-4749-9c67-18f237d6e85f">

**Comment by zheyichn** [comment]
## Summary
- Performance score took big hit on mobile devices because of `largest contentful paint` time of 7.1 seconds, and a `total blocking time` of 340ms.
- Some less unurgent issues for performance are similar to other pages:
    - Accessibility points deducted from misue of `aria-*` attribute on elements. This issue has been reported in #727 previously, but currently wontfix since it came from NextUI.
    - SEO requires links to be crawlable.
    
## Improvement recommendations

1. Explore how to reduce content loading time/ blocking time. (Performance on mobile)
2. Increase contrast ratio for some table headers. (Accessibility)
3. Resolve the aria-* mismatch with role issue of the menu button, possibily by refactoring the menu component as discussed in https://github.com/CodeForPhilly/clean-and-green-philly/issues/727. (Accessibility)
4. Make links crawlable to search engines. (SEO)
